# Generated by Django 4.1.4 on 2022-12-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('desc', models.CharField(max_length=1300)),
                ('img', models.CharField(max_length=1300)),
            ],
        ),
    ]
