# Generated by Django 4.1.4 on 2022-12-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
