# Generated by Django 4.1.4 on 2022-12-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_tool_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='longDesc',
            field=models.CharField(default='', max_length=2300),
        ),
    ]
